# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'banking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\x12\x08org.paul\"4\n\x0e\x44\x65positRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"5\n\x0fWithdrawRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"K\n\x0fTransferRequest\x12\x14\n\x0c\x66rom_account\x18\x01 \x01(\t\x12\x12\n\nto_account\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"$\n\x0e\x42\x61lanceRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"J\n\x11OperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bnew_balance\x18\x03 \x01(\x01\"6\n\x0f\x42\x61lanceResponse\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\x32\x9d\x02\n\x0e\x42\x61nkingService\x12@\n\x07\x44\x65posit\x12\x18.org.paul.DepositRequest\x1a\x1b.org.paul.OperationResponse\x12\x42\n\x08Withdraw\x12\x19.org.paul.WithdrawRequest\x1a\x1b.org.paul.OperationResponse\x12\x42\n\x08Transfer\x12\x19.org.paul.TransferRequest\x1a\x1b.org.paul.OperationResponse\x12\x41\n\nGetBalance\x12\x18.org.paul.BalanceRequest\x1a\x19.org.paul.BalanceResponseB\x0b\n\x07\x62\x61nkingP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\007bankingP\001'
  _globals['_DEPOSITREQUEST']._serialized_start=27
  _globals['_DEPOSITREQUEST']._serialized_end=79
  _globals['_WITHDRAWREQUEST']._serialized_start=81
  _globals['_WITHDRAWREQUEST']._serialized_end=134
  _globals['_TRANSFERREQUEST']._serialized_start=136
  _globals['_TRANSFERREQUEST']._serialized_end=211
  _globals['_BALANCEREQUEST']._serialized_start=213
  _globals['_BALANCEREQUEST']._serialized_end=249
  _globals['_OPERATIONRESPONSE']._serialized_start=251
  _globals['_OPERATIONRESPONSE']._serialized_end=325
  _globals['_BALANCERESPONSE']._serialized_start=327
  _globals['_BALANCERESPONSE']._serialized_end=381
  _globals['_BANKINGSERVICE']._serialized_start=384
  _globals['_BANKINGSERVICE']._serialized_end=669
# @@protoc_insertion_point(module_scope)
